Feature/stageclasses
eqasim-org/synpp pull request #56
Opened 2021-05-06 13:58 UTC by davibicudo

This PR adresses issues #52 and #53. It doesn't cover the issues entirely however.
@sebhoerl let me know what you think, perhaps you have some other ideas in mind on how to solve the same issues.

2021-05-06 14:01 UTC, davibicudo commented
I was also able to use this when running arbitrary code in Jupyter, which may also be nice for the caching (although IPython also has other solutions for that): 
![image](https://user-images.githubusercontent.com/28100741/117311159-3c913f00-ae84-11eb-91a7-0076e4d862aa.png)

2021-05-10 11:28 UTC, sebhoerl requested changes

2021-05-10 11:28 UTC, sebhoerl commented on src/synpp/pipeline.py
> +            os.mkdir(working_directory)
I see the point, but so far I was deliberately avoiding this, to make sure that the user is 100% aware where all the caching files will go. Maybe we can add a config flag, which is usually "false" like "auto_generate_working_directory" ?

2021-05-10 11:28 UTC, sebhoerl commented on src/synpp/pipeline.py
> +    if rerun_required:
Is this covered by a unit test ? If not, can you add one ?

2021-05-10 11:28 UTC, sebhoerl commented on src/synpp/pipeline.py
> +    def run_single(self, descriptor, config={}, rerun_if_cached=False, dryrun=False, verbose=False):
Really nice! If it had a unit test, would be even better :)

2021-05-10 11:30 UTC, sebhoerl commented
Really nice, I like the jupyter integration! It would be nice if you could add some unit tests so this is robust for the future. Thanks!

2021-05-17 09:35 UTC, davibicudo commented
Sounds good, I'll increment the PR with a couple tests then.

2021-05-27 10:41 UTC, sebhoerl approved these changes

2021-05-27 10:42 UTC, sebhoerl commented
Please update the `CHANGELOG.md` then it should be good to go :) Thanks!

2021-05-27 16:43 UTC, merged